sudo: required
dist: trusty

language: cpp

os:
    - linux
    - osx

env:
    - CONFIG=Release

python:
    - "3.5"

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty
      && sudo apt-add-repository -y ppa:george-edison55/cmake-3.x
      && sudo apt-get -qq update
      && sudo apt-get -qq install build-essential qt55tools qt55base libpython3-dev cmake
      && QTDIR="/opt/qt55"
      && PATH="$QTDIR/bin:$PATH"
      && qt55-env.sh 
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      && brew install qt5
      && brew linkapps qt5
      && brew link --force qt5
      && brew install python3
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake .
        ;
    else
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake .
        ;
    fi
    && make -j 3
    
after_failure:
  - cat /home/travis/build/LaTruelle/patagui/pythonqt/src/PythonQt-External-stamp/PythonQt-External*.log
