sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  - CONFIG=Release

python:
    - "3.5"

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-i386.tar.gz --no-check-certificate
      && tar -xzf cmake-3.3.2-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.3.2-Linux-i386/* /usr
      && sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty
      && sudo apt-get -qq update
      && sudo apt-get -qq install qt55tools qt55base libpython3-dev gcc g++
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      && brew install qt5
      && brew linkapps qt5
      && brew link --force qt5
      && brew install python3
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake .
        ;
    else
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake .
        ;
    fi
    && make -j 3
